name: fundsup
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl_phone_number_input: ^0.7.0+2
  otp_text_field: ^1.1.3
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.38
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  getwidget: ^3.0.1
  modal_bottom_sheet: ^2.1.0
  date_field: ^3.0.1
  dropdown_button2: ^1.7.0
  flutter_speed_dial: ^6.0.0
  syncfusion_flutter_datepicker: ^20.2.43
  azlistview: ^2.0.0
  alphabet_list_scroll_view: ^2.0.0
  alphabet_scroll_view: ^0.3.1

dev_dependecies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
      - family: Montserrat
      - fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300